name: logger_csx
description: Small, easy to use and extensible logger which prints beautiful logs.
version: 0.0.2
homepage: https://github.com/KirstenDunst/logger

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dev_dependencies:
  test: any
  pedantic: ^1.9.0
