name: logger_csx
description: Small, easy to use and extensible logger which prints beautiful logs.
version: 0.0.3
homepage: https://github.com/KirstenDunst/logger

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.9.0
