name: logger_csx
description: Small, easy to use and extensible logger which prints beautiful logs.
version: 0.0.1
homepage: https://github.com/KirstenDunst/logger

environment:
  sdk: ">=2.7.0-0 <3.0.0"

dev_dependencies:
  test: any
  pedantic: ^1.9.0
